FROM ubuntu:20.04

# Install tools and libraries
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -qq golang-1.14 pkg-config libpcap-dev libhyperscan-dev yarnpkg

COPY . /caronte

WORKDIR /caronte

RUN ln -sf ../lib/go-1.14/bin/go /usr/bin/go && \
    go mod download && \
    go build && \
    cd frontend && \
	yarnpkg install && \
	yarnpkg build

CMD ./caronte
