FROM golang:1.19

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -qq \
	git \
	pkg-config \
	libpcap-dev \
	libhyperscan-dev

WORKDIR /caronte

COPY . /caronte

RUN go mod download && \
    go build github.com/eciavatta/caronte/cmd/caronte

ENTRYPOINT go test -v -race -covermode=atomic ./...
